'use strict';
const $=id=>document.getElementById(id),NS='http://www.w3.org/2000/svg';
function el(tag,attrs={},text){const n=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);if(text!==undefined)n.textContent=text;return n;}
function rng(seed){return()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};}
let chordRandom=rng(27092026),coinRandom=rng(27102026),chordTimer=null,coinTimer=null,run=0;
const counts=[0,0,0],longs=[0,0,0],history=[[],[],[]];
function stopChord(){clearInterval(chordTimer);chordTimer=null;$('chord-animate').setAttribute('aria-pressed','false');$('chord-animate').textContent='Animate 100';}
function stopCoin(){clearInterval(coinTimer);coinTimer=null;$('coin-animate').setAttribute('aria-pressed','false');$('coin-animate').textContent='Animate 100';}
function tab(name){if(!['bertrand','events','frequency'].includes(name))name='bertrand';stopChord();stopCoin();document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.tab===name)));document.querySelectorAll('.section').forEach(s=>s.hidden=s.id!==name);historyReplace(name);}
function historyReplace(name){try{window.history.replaceState(null,'','#'+name);}catch{}}
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>tab(b.dataset.tab)));
function chordDraw(i){let a,b,d,theta;const u=chordRandom(),v=chordRandom();if(i===0){a=[Math.cos(2*Math.PI*u),Math.sin(2*Math.PI*u)];b=[Math.cos(2*Math.PI*v),Math.sin(2*Math.PI*v)];d=Math.hypot((a[0]+b[0])/2,(a[1]+b[1])/2);}else{d=i===1?u:Math.sqrt(u);theta=2*Math.PI*v;const h=Math.sqrt(1-d*d),cx=d*Math.cos(theta),cy=d*Math.sin(theta);a=[cx-h*Math.sin(theta),cy+h*Math.cos(theta)];b=[cx+h*Math.sin(theta),cy-h*Math.cos(theta)];}counts[i]++;if(d<.5)longs[i]++;history[i].push({a,b,long:d<.5});if(history[i].length>50)history[i].shift();}
function chordRender(){['a','b','c'].forEach((key,i)=>{const svg=$('chord-'+key);svg.replaceChildren();svg.append(el('circle',{cx:160,cy:160,r:138,fill:'none',stroke:'#8298ad','stroke-width':1.5}));history[i].forEach((c,j)=>{svg.append(el('line',{x1:160+138*c.a[0],y1:160+138*c.a[1],x2:160+138*c.b[0],y2:160+138*c.b[1],stroke:c.long?'#006d77':'#ad4a26','stroke-width':j===history[i].length-1?3:1,'stroke-dasharray':c.long?'none':'4 3',opacity:j===history[i].length-1?1:.23}));});svg.append(el('circle',{cx:160,cy:160,r:69,fill:'none',stroke:'#172d43','stroke-dasharray':'5 5'}));svg.append(el('circle',{cx:160,cy:160,r:3,fill:'#172d43'}));$('result-'+key).textContent=counts[i]?`${longs[i]} / ${counts[i]} = ${(longs[i]/counts[i]).toFixed(3)}`:'0 draws';});}
function chords(n){for(let k=0;k<n;k++)for(let i=0;i<3;i++)chordDraw(i);chordRender();$('chord-status').textContent=`${counts[0].toLocaleString()} draws per generator.`;}
$('chord-step').onclick=()=>chords(1);$('chord-batch').onclick=()=>{stopChord();chords(1000);};$('chord-reset').onclick=()=>{stopChord();counts.fill(0);longs.fill(0);history.forEach(h=>h.length=0);chordRandom=rng(27092026);chordRender();$('chord-status').textContent='Reset to the original seed.';};
$('chord-animate').onclick=()=>{if(chordTimer){stopChord();return;}if(matchMedia('(prefers-reduced-motion: reduce)').matches){chords(100);return;}let remaining=100;$('chord-animate').setAttribute('aria-pressed','true');$('chord-animate').textContent='Stop';chordTimer=setInterval(()=>{chords(1);if(--remaining===0)stopChord();},80);};
const selected=new Set([2,4,6]);
function eventRender(){const fair=$('measure').value==='fair',parity=$('information').value==='parity';const arr=[...selected].sort((a,b)=>a-b);$('faces').replaceChildren();for(let i=1;i<=6;i++){const b=document.createElement('button');b.type='button';b.className='face';b.setAttribute('aria-pressed',String(selected.has(i)));b.setAttribute('aria-label',`Face ${i}, full-model weight ${fair?'1/6':i+'/21'}`);b.innerHTML=`${i}<small>${fair?'1/6':i+'/21'}</small>`;b.onclick=()=>{selected.has(i)?selected.delete(i):selected.add(i);eventRender();};$('faces').append(b);}const mask=arr.join(','),allowed=!parity||['','1,2,3,4,5,6','1,3,5','2,4,6'].includes(mask);$('event-set').textContent='A = '+(arr.length?'{'+arr.join(', ')+'}':'∅');const num=fair?arr.length:arr.reduce((a,b)=>a+b,0),den=fair?6:21;$('event-result').textContent=allowed?`A belongs to F. P(A) = ${num}/${den} = ${(num/den).toFixed(4)}. P(Aᶜ) = ${den-num}/${den}.`:'A does not belong to the selected F. P(A) is undefined in this model.';$('event-f').textContent=parity?'F = {∅, {1,3,5}, {2,4,6}, Ω}. These four sets are closed under complements and countable unions.':'F = 2^Ω: all 64 subsets are events. Uniform counting is valid only for the fair weights.';}
$('measure').onchange=eventRender;$('information').onchange=eventRender;document.querySelectorAll('[data-event]').forEach(b=>b.onclick=()=>{const before=new Set(selected);selected.clear();for(let i=1;i<=6;i++)if(({even:i%2===0,high:i>3,six:i===6,all:true,none:false,complement:!before.has(i)})[b.dataset.event])selected.add(i);eventRender();});
let tosses=0,heads=0,values=[],p=Number($('coin-p').value);$('coin-p-value').value=p.toFixed(2);
function coinRender(){const svg=$('frequency-plot');svg.replaceChildren();const x0=64,x1=970,y0=24,y1=316,max=Math.max(100,tosses);const x=n=>x0+(x1-x0)*n/max,y=v=>y1-(y1-y0)*v;svg.append(el('rect',{x:x0,y:y0,width:x1-x0,height:y1-y0,fill:'none',stroke:'#c9d6e3'}));for(const v of[0,.25,.5,.75,1]){svg.append(el('line',{x1:x0,y1:y(v),x2:x1,y2:y(v),stroke:'#e4ebf2'}));svg.append(el('text',{x:x0-10,y:y(v)+5,'text-anchor':'end',fill:'#172d43','font-size':16},v.toFixed(2)));}for(const v of[0,Math.round(max/2),max])svg.append(el('text',{x:x(v),y:y1+25,'text-anchor':v===0?'start':v===max?'end':'middle',fill:'#172d43','font-size':16},String(v)));svg.append(el('text',{x:510,y:372,'text-anchor':'middle',fill:'#172d43','font-size':18},'Toss count n'));svg.append(el('text',{x:18,y:170,transform:'rotate(-90 18 170)','text-anchor':'middle',fill:'#172d43','font-size':18},'Fraction of heads'));svg.append(el('line',{x1:x0,y1:y(p),x2:x1,y2:y(p),stroke:'#ad4a26','stroke-dasharray':'7 5','stroke-width':2}));if(values.length){const pts=values.map((v,i)=>`${x(i+1)},${y(v)}`).join(' ');svg.append(el('polyline',{points:pts,fill:'none',stroke:'#003f87','stroke-width':2}));svg.append(el('circle',{cx:x(tosses),cy:y(heads/tosses),r:4,fill:'#003f87'}));}$('coin-result').textContent=tosses?`${heads} heads in ${tosses} tosses · observed ${(heads/tosses).toFixed(4)} · model p = ${p.toFixed(2)}`:'No tosses yet · model p = '+p.toFixed(2);}
function coins(n){for(let i=0;i<n&&tosses<20000;i++){tosses++;if(coinRandom()<p)heads++;values.push(heads/tosses);}coinRender();if(tosses>=20000)stopCoin();}
function resetCoin(){stopCoin();tosses=0;heads=0;values=[];coinRandom=rng(27102026+(++run));coinRender();}
$('coin-p').oninput=e=>{p=Number(e.target.value);$('coin-p-value').value=p.toFixed(2);resetCoin();};$('coin-step').onclick=()=>coins(1);$('coin-batch').onclick=()=>{stopCoin();coins(1000);};$('coin-reset').onclick=resetCoin;$('coin-animate').onclick=()=>{if(coinTimer){stopCoin();return;}if(matchMedia('(prefers-reduced-motion: reduce)').matches){coins(100);return;}let remaining=100;$('coin-animate').setAttribute('aria-pressed','true');$('coin-animate').textContent='Stop';coinTimer=setInterval(()=>{coins(1);if(--remaining===0)stopCoin();},65);};
window.addEventListener('hashchange',()=>tab(location.hash.slice(1)));tab(location.hash.slice(1));chordRender();eventRender();coinRender();
